name: Node.JS CI/CD

on:
  push:
    branches: [main]

jobs:
  
  test_node_12:
    name: Test on Node 12
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      
      - name: NPM install, build and test
        run: |
          npm install
          npm test
        env:
          DBHOST: ${{ secrets.DBHOST }}  
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}  
          JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}  